### ISSUE TITLE
Update translations partner information for estonia

### ISSUE THREAD

**Issue by juliafallon** [rightsstatements/website#4]
Can we please update the estonian translation partner info on http://rightsstatements.org/en/documentation/translations.html 

FROM: Expression of interest received, no translation partner selected yet

UPDATE TO:  Translation partner: Wikimedia Eesti and Estonian Photographic Heritage Society 

With urls https://ee.wikimedia.org/wiki/Esileht and http://fotoparand.org.ee/wp/eng/ accordingly?

**Comment by anarchivist** [comment]
Thanks @juliafallon - subitting changes now. This repo isn't the one we use primarily for the website - that's https://github.com/rightsstatements/rightsstatements.github.io .
